CREATE TABLE LT_EXTRACT_DATA
(
    LT_EXTRACT_DATA_KEY SERIAL PRIMARY KEY,
    USER_ID             VARCHAR(255) NOT NULL,
    DOCUMENT_NAME       VARCHAR(255) NOT NULL,
    PAGE_COUNT          INT4         NOT NULL DEFAULT 1,
    EXTRACT_DATE_TIME   TIMESTAMP    NOT NULL
);

CREATE TABLE LT_TRANSLATE_DATA
(
    LT_TRANSLATE_DATA_KEY SERIAL PRIMARY KEY,
    USER_ID               VARCHAR(255) NOT NULL,
    DOCUMENT_NAME         VARCHAR(255) NOT NULL,
    TEXT_LENGTH           INT4         NOT NULL,
    TRANSLATE_DATE_TIME   TIMESTAMP    NOT NULL
);
